name: Shell commands

on: [push, pull_request]
#on:
  #schedule:
    #- cron: "0/2 * * * *" 
    #At every 2nd minute from 0 through 59.”

    #- cron: "0/6 * * * *"
    #At every 6th minute from 0 through 59.”


  #push:
  #pull_request:
    #types: [closed,assigned,opened,reopened]
jobs:
  test-on-windows:
    runs-on: self-hosted
    steps:
      - name: checking some basic windows commands
        run:     
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echoing string 
        run: echo "hello vinodh welcome to GHA"
      - name : echo npm versions
        run : |
          npm -v
          node -v 
      - name: Running some python commands
        run : |
          import platform
          print(platform.processor())   
        shell: python   
      - name: Checkout some Code 
        uses : actions/checkout@v1
      - name : checking file after checkout  
        run: |
          ls -lrtha
          pwd
          echo " just added"

  run-windows-commands:
    #runs-on: self-hosted
    runs-on: [self-hosted, windows-hem1, Windows] we can use this labels as well 
    steps:
      - name: Getting current location
        run : Get-Location
      - name : running bash command
        run : pwd
      - name: running one more bash
        run : Get-Service
        #shell : bash
        #sshell will not work in windows
